Routers = {
    "TE100-S5": {
        "Model": "TE100-S5",
        "Product Title": "5-Port 10/100Mbps Fast Ethernet Switch",
        "10/100 Mbps": "5x",
        "Forwarding Capacity": "1Gbps",
        "Data RAM Buffering": "384Kbytes",
        "802.3x Flow Control": "+",
        "MAC address entries": "2k",
        "enclosure Material": "Plastic",
        "GR66Nnet": "-",
        "Warranty": "3-year limited",
    },
    "TE100-S8": {
        "Model": "TE100-S8",
        "Product Title": "8-Port 10/100Mbps Fast Ethernet Switch",
        "10/100 Mbps": "8x",
        "Forwarding Capacity": "1.6Gbps",
        "Data RAM Buffering": "512Kbytes",
        "802.3x Flow Control": "+",
        "MAC address entries": "2k",
        "enclosure Material": "Plastic",
        "GR66Nnet": "-",
        "Warranty": "3-year limited",
    },
    "TE100-S50g": {
        "Model": "TE100-S50g",
        "Product Title": "5-Port 10/100Mbps GREENnet Switch",
        "10/100 Mbps": "5x",
        "Forwarding Capacity": "1Gbps",
        "Data RAM Buffering": "384Kbytes",
        "802.3x Flow Control": "+",
        "MAC address entries": "1k",
        "enclosure Material": "Metal Desktop",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S80g": {
        "Model": "TE100-S80g",
        "Product Title": "8-Port 10/100Mbps GREENnet Switch",
        "10/100 Mbps": "8x",
        "Forwarding Capacity": "1.6Gbps",
        "Data RAM Buffering": "768Kbytes",
        "802.3x Flow Control": "+",
        "MAC address entries": "1k",
        "enclosure Material": "Metal Desktop",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S16g": {
        "Model": "TE100-S16g",
        "Product Title": "16-Port 10/100Mbps GREENnet Switch",
        "10/100 Mbps": "16x",
        "Forwarding Capacity": "3.2Gbps",
        "Data RAM Buffering": "1.25Mbits",
        "802.3x Flow Control": "+",
        "MAC address entries": "8k",
        "enclosure Material": "Metal Rackmount",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
    "TE100-S24g": {
        "Model": "TE100-S24g",
        "Product Title": "24-Port 10/100Mbps GREENnet Switch",
        "10/100 Mbps": "24x",
        "Forwarding Capacity": "4.8Gbps",
        "Data RAM Buffering": "1.25Mbits",
        "802.3x Flow Control": "+",
        "MAC address entries": "8k",
        "enclosure Material": "Metal Rackmount",
        "GR66Nnet": "+",
        "Warranty": "3-year limited",
    },
}
param = input("Введите название параметра:")
value = input("Введите его значение:")
for k, v in model.items():
    if v[param] == value:
        print(k)